### ISSUE TITLE
Replace Prettier/ESLint/StyleLint with BiomeJs

### ISSUE THREAD

**Issue by arvigeus** [arvigeus/nixos-config#33]
- [x] JS formatter
- [x] JS Linter
- [ ] CSS Formatter ([in progress](https://github.com/biomejs/biome/issues/1285))
- [ ] CSS Linter ([parser in progress](https://github.com/biomejs/biome/issues/268))
- [ ] Sort TailwindCSS classes ([in progress](https://github.com/biomejs/biome/issues/1274))

[VS Code Extension](https://marketplace.visualstudio.com/items?itemName=biomejs.biome)

**Comment by arvigeus** [comment]
[Language Support](https://biomejs.dev/internals/language-support/)
