### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by arvigeus** [arvigeus/nixos-config#34]
This contains pretty much everything in terms of explanations: <https://github.com/mikeroyal/NixOS-Guide>

- <https://wiki.nixos.org/wiki/Cheatsheet>
- <https://nix.dev/>

**Comment by arvigeus** [comment]
Gaming section:

- [ ] Explain different components, what they do, and how they work together
  - [ ] [MangoHud + GOverlay](https://www.gamingonlinux.com/2022/07/goverlay-for-configuring-the-mangohud-performance-overlay-new-release-out/)
  - [ ] [protonup-qt](https://davidotek.github.io/protonup-qt/)
  - [ ] [gamescope](https://github.com/ValveSoftware/gamescope)
  - [ ] [gamemode](https://github.com/FeralInteractive/gamemode)
  - [ ] [protontricks](https://github.com/Matoking/protontricks)
- [ ] Steam
  - [ ] [SteamDB](https://steamdb.info)
  - [ ] [steam-tracker](https://steam-tracker.com/) (delisted games and other stats)
  - [ ] [ProtonDB](https://www.protondb.com/)

Example repos:

- <https://github.com/iggut/GamiNiX>

---

## Steam

### Run Steam in Big Picture Mode

```sh
steam -gamepadui -steamdeck
```

### Run Steam in HDPI mode

```
Environment variables: GDK_SCALE=2 STEAM_FORCE_DESKTOPUI_SCALING=2.0
Program: steam
Arguments: %U
```

## Gamescope

### Read more

- [ArchWiki: Gamescope](https://wiki.archlinux.org/title/Gamescope)
- [Linux Gaming: Gamescope](https://linux-gaming.kwindu.eu/index.php?title=Gamescope)

## System76 Scheduler

System76 scheduler replaces `gamemode` functionality and do not require a launch option to function properly.

## MangoHud

### Install

```nix
environment.systemPackages = with pkgs; [
  mangohud
];
```

### Enable for all Vulkan games

```nix
environment.sessionVariables = {
  MANGOHUD = "1";
};
```

### Keyboard commands

- `RShift+F12` – Toggle overlay
- `RShift+F11` – Change overlay position
- `LShift+F2` – Toggle logging
- `LShift+F4` – Reload config

### Test MangoHud

```sh
mangohud glxgears
```

```sh
mangohud glxgears
```

### Start a Steam game with MangoHud

- Right-click the game
- Select `Properties...`
- Set Launch Options to: `mangohud %command%`

Have to be set for each game.

### Use GameMode with MangoHud

```sh
mangohud gamemoderun ...
```

### Read more

- [ArchWiki: MangoHud](https://wiki.archlinux.org/title/MangoHud)

## Upscaling

Upscaling is the process of enhancing the resolution or frame rate of an image or video sequence. It involves generating additional pixel data to display higher-resolution output on screens that support finer details or creating interpolated frames in a video to increase smoothness and reduce motion blur.

### Temporal Upsampling (Temporal Super Resolution)
Temporal Upsampling increases the frame rate of video content without changing the resolution. By analyzing the motion between frames, it generates intermediate frames to create a smoother, high-frame-rate output. It's often used in post-production for videos to achieve a fluid visual experience, especially for high-speed scenes or to create slow-motion effects.

#### Read mode

- [Enabling Temporal Super Resolution (DLSS) in Unreal Engine 4 Titles (With Examples)](https://www.reddit.com/r/SteamDeck/comments/zqgj7s/enabling_temporal_super_resolution_dlss_in_unreal/)
- [Screen Percentage with Temporal Upsample](https://docs.unrealengine.com/4.27/en-US/RenderingAndGraphics/ScreenPercentage/)

### NVIDIA DLSS (Deep Learning Super Sampling)

Developed by NVIDIA, DLSS takes a different, more futuristic route. It uses machine learning and AI to upscale images, rendering them at a lower resolution for performance efficiency, and then intelligently scaling up while enhancing details and sharpness. This not only improves image quality in real-time scenarios like gaming but also offers substantial performance gains by offloading the GPU's rendering burden.

#### Read more

- [SteamDB: NVIDIA DLSS](https://steamdb.info/tech/SDK/NVIDIA_DLSS/)

### AMD FSR (FidelityFX Super Resolution)

AMD's answer to DLSS, FSR, stands as a more hardware-agnostic solution. It lacks the AI component, relying instead on spatial upscaling techniques to enhance image resolution. This approach ensures broader compatibility across different GPUs, including those without dedicated AI or machine learning capabilities.

TODO:

- [ ] Setup with Wine/Proton-GE
- [ ] Setup with Gamescope

#### Read mode

- [Linux Gaming: FSR](https://linux-gaming.kwindu.eu/index.php?title=FSR_-_FidelityFX_Super_Resolution)
- [SteamDB: AMD FSR2](https://steamdb.info/tech/SDK/AMD_FSR2/)

### Intel XeSS

Uses AI like DLSS, but works for broader compatibility across different GPUs like FSR

#### Read more

- [SteamDB: Intel XeSS](https://steamdb.info/tech/SDK/Intel_XeSS/)

### Comparison

DLSS and FSR improve frame rates by rendering at lower resolutions and then upscaling, with DLSS generally providing better image quality due to AI. Temporal Upsampling specifically boosts frame rates in videos.

## TODO

- Consolidate everything under `Steam`
- <https://universal-blue.discourse.group/t/bazzite-gaming-guide/31>
- Decky
- [GeForce Now](https://arstechnica.com/gaming/2024/05/streaming-games-with-geforce-now-on-steam-deck-is-much-easier-now/)
- [Netris](https://github.com/nestriness/nestri) (GeForceNow alternative)
- `STEAM_FORCE_DESKTOPUI_SCALING=1.5 steam`

**Comment by arvigeus** [comment]
KDE section:

- [KDE config file paths](https://github.com/shalva97/kde-configuration-files)
- [15 KDE Plasma tricks, tools, apps, and widgets I use to be more productive](https://www.youtube.com/watch?v=Sungl8gWU_8)

**Comment by arvigeus** [comment]
[Selectively Using Service Modules from NixOS Unstable](https://lgug2z.com/articles/selectivey-using-service-modules-from-nixos-unstable/)

**Comment by arvigeus** [comment]
## Hardware

### AMD Drivers

#### RADV

A community-driven Vulkan driver, part of the Mesa project (also backed by Valve). It offers good performance (allegedly better than AMDVLK) and wide compatibility with Vulkan applications. It's the default choice in many Linux distributions.

#### AMDVLK

The open-source Vulkan driver provided by AMD. It is built on the shared Vulkan core used in both open-source and proprietary drivers.

The AMDVLK drivers can be enabled with `hardware.amdgpu.amdvlk = true;` (`nixos-hardware` module). They can used in addition to the Mesa RADV drivers - the program will choose which one to use. To force RADV, set `environment.variables.AMD_VULKAN_ICD = "RADV";`

#### AMDGPU-PRO

AMD's proprietary driver optimized for professional and workstation use, featuring extended support for enterprise environments and additional optimizations. Generally, it doesn't offer more features or performance.

To enable it: `services.xserver.videoDrivers = [ "amdgpu-pro" ];`

NOTE: It's often broken in nixpkgs.

### Read more

- [ArchWiki: Vulkan](https://wiki.archlinux.org/title/Vulkan)
- [NixOS Wiki: AMD GPU](https://wiki.nixos.org/wiki/AMD_GPU)
- [ArchWiki: AMDGPU](https://wiki.archlinux.org/title/AMDGPU)
- [ArchWiki: AMDGPU PRO](https://wiki.archlinux.org/title/AMDGPU_PRO)
- [Phoronix: AMDVLK vs. Mesa RADV Radeon Vulkan Driver Performance On Linux](https://www.phoronix.com/review/amdvlk-radv-rx7900)

### TODO

- [ ] [Overclocking with CoreCtrl](https://linux-gaming.kwindu.eu/index.php?title=CoreCtrl)
- [ ] Explain `nixos-hardware`
- [ ] How to determine which driver I'm using
- [ ] OpenCL?
- [ ] supergfxd
- [ ] asusctl
- [ ] How to check battery draw?

**Comment by arvigeus** [comment]
DNS:

|                    | **Primary**         | **Secondary**         |
|--------------------|---------------------|-----------------------|
| **Cloudflare**     | `1.1.1.1`           | `1.0.0.1`             |
| **Google**         | `8.8.8.8`           | `8.8.4.4`             |
| **OpenDNS**        | `208.67.222.222`    | `208.67.220.220`      |
| **Quad9**          | `9.9.9.9`           | `149.112.112.112`     |
| **Level3 / CenturyLink** | `4.2.2.1`     | `4.2.2.2`             |
| **Verisign**       | `64.6.64.6`         | `64.6.65.6`           |
| **Comodo Secure DNS** | `8.26.56.26`     | `8.20.247.20`         |
| **DNS.WATCH**      | `84.200.69.80`      | `84.200.70.40`        |
| **CleanBrowsing**  | `185.228.168.9`     | `185.228.169.9`       |
| **Alternate DNS**  | `76.76.19.19`       | `76.223.122.150`      |
| **AdGuard DNS**    | `94.140.14.14`      | `94.140.15.15`        |

Also: NextDNS

**Comment by arvigeus** [comment]
MPV

Check if shaders are loaded: `Shift + i`, then press `2`. Also, press `` ` `` (backtick) to check for errors

**Comment by arvigeus** [comment]
AI

[Making AMD GPUs competitive for LLM inference](https://blog.mlc.ai/2023/08/09/Making-AMD-GPUs-competitive-for-LLM-inference)
